name: exbert
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - pip>=19.0.3
  - python=3.7
  - h5py
  - spacy
  - boto3
  - regex
  - faiss-cpu
  - numpy=1.16.2
  - olefile=0.46
  - pickleshare=0.7.5
  - pillow=5.4.1
  - pip=19.0.3
  - pytorch=1.0.1
  - sacremoses
  - mypy
  - pytest
  - pip:
    - fastapi[all]
    - async-lru
    - sentencepiece
    - tokenizers>=0.5.1