apiVersion: v1
kind: Service
metadata:
  name: <APPNAME_PLACEHOLDER>
  namespace: visdemos
  labels:
    run: <APPNAME_PLACEHOLDER>
spec:
  type: NodePort
  selector:
    run: <APPNAME_PLACEHOLDER>
  ports:
   - protocol: TCP
     port: 80
     targetPort: 5050

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/allow-http: "false"
    ingress.kubernetes.io/ssl-redirect: "true"
    # kubernetes.io/ingress.class: public-iks-k8s-nginx ## <--- This line is for K8S ingress ONLY (REMOVE it from OCP ingress)
  name: <APPNAME_PLACEHOLDER>
  namespace: visdemos
spec:
  rules:
  - host: <APPNAME_PLACEHOLDER>.draco.res.ibm.com
    http:
      paths:
      - backend:
          service:
            name: <APPNAME_PLACEHOLDER>  # <--- Name of service you want to expose with ingress host; it should be of "type: NodePort"
            port:
              number: 80 # <---- This is your service port ... NOT THE NODEPORT
        path: "/"
        pathType: ImplementationSpecific
  tls:
  - secretName: tls-secret
    hosts:
    - '*.draco.res.ibm.com' ## <--- this wildcard host name is required
    - <APPNAME_PLACEHOLDER>.draco.res.ibm.com